name: Security Scanning Automation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly on Monday at 6 AM UTC
    - cron: '0 6 * * 1'

jobs:
  dependency-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'microservices-security'
        path: '.'
        format: 'HTML'
        out: 'reports'
        
    - name: Upload dependency scan report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-scan-report
        path: reports/
        retention-days: 30

  code-scan:
    name: Code Security Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install ESLint security plugin
      run: |
        npm install --save-dev eslint-plugin-security
        npm install --save-dev @typescript-eslint/parser
        
    - name: Run ESLint security analysis
      run: |
        npx eslint src/ tests/ --config .eslintrc.security.js --format json --output-file eslint-security-report.json || true
        
    - name: Run CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        languages: javascript
        
    - name: Upload code security report
      uses: actions/upload-artifact@v4
      with:
        name: code-security-report
        path: eslint-security-report.json
        retention-days: 30

  secret-scan:
    name: Secret Detection Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run TruffleHog secret scan
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: >
          --regex
          --entropy=False
          --max_depth=20
        
    - name: Run Gitleaks secret scan
      uses: gitleaks/gitleaks-action@v2
      with:
        config-path: .gitleaks.toml
        
    - name: Upload secret scan report
      uses: actions/upload-artifact@v4
      with:
        name: secret-scan-report
        path: gitleaks-report.json
        retention-days: 30

  vulnerability-assessment:
    name: Vulnerability Assessment
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Run Snyk vulnerability scan
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
        
    - name: Run npm audit
      run: |
        npm audit --audit-level=high --json > npm-audit-report.json || true
        
    - name: Upload vulnerability reports
      uses: actions/upload-artifact@v4
      with:
        name: vulnerability-reports
        path: |
          npm-audit-report.json
          snyk-report.json
        retention-days: 30

  security-summary:
    name: Security Summary Report
    runs-on: ubuntu-latest
    needs: [dependency-scan, code-scan, secret-scan, vulnerability-assessment]
    
    steps:
    - name: Download all security reports
      uses: actions/download-artifact@v4
      with:
        path: security-reports/
        
    - name: Generate security summary
      run: |
        echo "Security Scan Summary" > security-summary.md
        echo "=====================" >> security-summary.md
        echo "" >> security-summary.md
        echo "Scan completed at: $(date)" >> security-summary.md
        echo "" >> security-summary.md
        echo "### Scan Results:" >> security-summary.md
        echo "- ✅ Dependency Scan: Completed" >> security-summary.md
        echo "- ✅ Code Security Analysis: Completed" >> security-summary.md
        echo "- ✅ Secret Detection: Completed" >> security-summary.md
        echo "- ✅ Vulnerability Assessment: Completed" >> security-summary.md
        echo "" >> security-summary.md
        echo "All security scans completed successfully." >> security-summary.md
        
    - name: Upload security summary
      uses: actions/upload-artifact@v4
      with:
        name: security-summary
        path: security-summary.md
        retention-days: 30